### ISSUE TITLE
Tutorial page coming soon?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [yuqiyuqitan/SPACEc#45]
Hi there, 

Thanks for the tool. I aim to analyze some multiplexed immunofluorescence image done with Vector Polaris (6 antibodies), and I am excited to give it a try with SPACEc. 

I wonder if the dedicated tutorial page will be available soon? For now, do you recommend looking through the paper and the notebooks at https://github.com/yuqiyuqitan/SPACEc/tree/master/notebooks?

A small note, the link to the sample tonsil data is broken: https://doi.org/10.5061/dryad.brv15dvj1

Looking forward to more updates.

**Comment by yuqiyuqitan** [comment]
Hi,

Thanks for your interest in SPACEc and let us know how it goes with using SPACEc for Vector Polaris! 

For tutorials, we have an online doc: https://spacec.readthedocs.io/en/latest/?badge=latest, and there are more detailed explanations in Supplementary Notes 2 in our preprint (p13-24): https://doi.org/10.1101/2024.06.29.601349.

The dryad link is still waiting to be published by the database. Try this link for the example data: https://datadryad.org/stash/share/OXTHu8fAybiINGD1S3tIVUIcUiG4nOsjjeWmrvJV-dQ

**Comment by denvercal1234GitHub** [comment]
Thanks, @yuqiyuqitan - I looked at the reference for the tonsil image. Could you confirm whether the link for example data above is mouse tonsil or spleen? Because in the preprint this data points to this reference but it looks like it is mouse spleen and not tonsil? 

"Yury Goltsev, Nikolay Samusik, Julia Kennedy-Darling, Salil Bhate, Matthew Hale, Gustavo Vazquez, Sarah Black, and Garry P Nolan. Deep profiling of mouse splenic architecture with CODEX multiplexed imaging. Cell, 174(4):968–981.e15, aug 2018. ISSN 00928674. doi: 10.1016/j.cell.2018.07.010."

**Comment by yuqiyuqitan** [comment]
Yes, it is tonsil. The reference is to cite for the CODEX machine.
