### ISSUE TITLE
Using StarDist cell segmentation within SPACEc?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [yuqiyuqitan/SPACEc#46]
Hi there, 

Thanks again for the tool. 

I had performed cell segmentation for my multiplexed immunofluorescence in QuPath using StartDist and obtained very good results. 

I could export the measurement values as a data frame for each segmented cell (in QuPath they are called cell detections) for every channel and continue from the Signal Processing in the SPACEc workflow. 

**Q1.** From the tutorial, it looks like it is simply a dataframe with each row is a cell and each column is a channel. Is there any particular modifications of the QuPath measurement exports I need to do in order for it to be fully compatible with SPACEc? 

This is how my export data frame looks like: 

<img width="1666" alt="Screenshot 2024-07-07 at 13 13 43" src="https://github.com/yuqiyuqitan/SPACEc/assets/62179082/b95ebfaa-1163-4468-93bf-50d302c8d006">

**Q2.** Is there a way to implement StarDist model directly in SPACEc?

**Q3.** Because the input in this way would be just the dataframe of the measurements and not the image. When I finish with the SPACEc analysis, do you have any resources to visualise the results on the section image?

**Comment by TKempchen** [comment]
Hi Quang,

**A1.** Your input should be compatible with SPACEc. The sp.pp.format function should handle this input if you specify the metadata columns you want to keep or drop. The result will be a dataframe with the normalized marker columns first, followed by the metadata columns. 

**A2.** Although not planned at the moment, we could think of implementing it in the future if more users request this feature. For now, I would recommend you either use StarDist outside SPACEc and import your data or try one of the included models (e.g. Mesmer) and see if you are satisfied with the performance for your dataset. However, I will evaluate if we can implement StarDist in a future update. 

**A3.** If you want to interactively visualize the cell centroids on top of your images, you can use TissUUmaps, which is installed together with SPACEc but can also be used as a standalone application (see the TissUUmaps website). If you just want to plot the cell centroids statically on top of an image, I would recommend using Matplotlib (a scatter plot on top of an image). 

I hope these answers give you a good start. If you need any more info, don't hesitate to ask.

**Comment by denvercal1234GitHub** [comment]
Hi, @TKempchen, 

I was trying to use the Docker image pulled, but upon opening the Jupyter notebook, the kernel kept dying so I decided to just follow installation for M1 in my local machine instead. 

<img width="790" alt="Screenshot 2024-07-09 at 22 35 18" src="https://github.com/yuqiyuqitan/SPACEc/assets/62179082/e726ba5e-beb7-42cf-ab11-ef9fac5be6e8">

Installing it locally, however, kept throwing error at `pip install spacec` as below. Do you have any advice?

```
OSError: [Errno 66] Directory not empty: '/private/var/folders/88/sbdxkfhj2cddjgzv4cxl8_680000gn/T/pip-install-q1omnno5/fastremap_26dbc5a92a754f66aea3886cee3a0915/.eggs/Cython-3.0.10-py3.9-macosx-10.9-x86_64.egg/Cython-3.0.10.dist-info' -> '/private/var/folders/88/sbdxkfhj2cddjgzv4cxl8_680000gn/T/pip-install-q1omnno5/fastremap_26dbc5a92a754f66aea3886cee3a0915/.eggs/Cython-3.0.10-py3.9-macosx-10.9-x86_64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for fastremap
Failed to build fastremap
ERROR: Could not build wheels for fastremap, which is required to install pyproject.toml-based projects
```

Thank you!

**Comment by denvercal1234GitHub** [comment]
https://github.com/yuqiyuqitan/SPACEc/issues/48 solved the issue with `fastremap` 

But issue with docker remained.

**Comment by TKempchen** [comment]
The Docker image is currently an AMD64 image. We are working on an ARM64 variant that should cause no problems when run on ARM platforms.
