### ISSUE TITLE
Installation for Mac M1

### ISSUE THREAD

**Issue by denvercal1234GitHub** [yuqiyuqitan/SPACEc#47]
Hi there, 

I noticed you guys have plan to add support for Mac M1, but it is not yet available. 

I decided to just use Docker as advised for now. Might I confirm that if using Docker as provided, I will not need to install "additional features" or use conda environment as mentioned at https://spacec.readthedocs.io/en/latest/readme.html#, right?

Thank you again. 

```
docker pull tkempchen/spacec:cpu
docker run -p 8888:8888 -p 5100:5100 spacec:cpu
```

**Comment by TKempchen** [comment]
Hi, 

please follow the recent installation guide for Apple M1/M2 from our readme file. If you use the Docker images consider that these were build on an x86 machine and do not natively run on ARM (yet). When running the Docker images you don't have to install anything, it will launch a Jupyter server that you can access via your webbrowser or a suitable IDE (e.g. VScode).

**Comment by denvercal1234GitHub** [comment]
Hi @TKempchen - a quick confirmation. I had successfully installed `spacec` on my M1, but in the  tutorial "https://spacec.readthedocs.io/en/latest/readme.html", it mentions installation of `GPU accelerated clustering` RAPIDS (which seems like it would not work for Mac M1) and `PyTorch` and `PyTorch Geometric`. 

On Mac M1, could I use OpenCL or Metal etc for these 2 features?

**Comment by TKempchen** [comment]
At the moment OpenCL or Metal are not supported due to multiple dependencies that require specific versions of PyTorch or Tensorflow.
