### ISSUE TITLE
FYI: this project requires CUDA 11

### ISSUE THREAD

**Issue by aowenson-imm** [yuqiyuqitan/SPACEc#52]
SPACEc requires DeepCell -> tensorflow 2.8.4 -> CUDA 11. With CUDA 12 I get this error:

```
>>> import spacec as sp
2024-07-24 14:10:37.305784: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'
```

**Comment by TKempchen** [comment]
Could you provide us with further information regarding the platform you are running on?

**Comment by aowenson-imm** [comment]
- server of Nvidia L40S, Ubuntu 22
- Nvidia driver version 535.183.01
- various CUDA versions available via GNU environment modules

I had followed your install instructions with CUDA 12 module activated, only discovered the error at end. Reinstalling with CUDA 11 allows me to import spacec.

**Comment by yuqiyuqitan** [comment]
Thank you for sharing. This is very valuable information. Even though SPACEc is running on CUDA 12 on our end, in the future, if others experience the same issue, we would recommend that they downgrade their CUDA version.
