### ISSUE TITLE
Not able to download data from Dryad

### ISSUE THREAD

**Issue by pranjalvaidya** [yuqiyuqitan/SPACEc#56]
Hello,

Thank you for the great work! 
I am having issues downloading the sample data from Dryad - to gives me error saying "You may not download this file."
Is there any other way to look at the sample data?

Thanks!

**Comment by TKempchen** [comment]
Hi, thank you for your interest in SPACEc! Unfortunately, this might be a Dryad error that is specific to your network or region. I checked the link and was able to download the data. Maybe check the proxy settings in you network or try another machine/network. I hope that helps.
Best, 
Tim
