### ISSUE TITLE
Compare Spatial context maps and motifs

### ISSUE THREAD

**Issue by Zach-Sten** [yuqiyuqitan/SPACEc#58]
Hello, I was wondering in the neighborhood analysis notebook if there were plans to add in some functions to assess the differences in motifs between sample groups similar to figure 5 in the tissue schematics map? This would be a great feature to get more out of the maps rather than just comparing them visually.

**Comment by TKempchen** [comment]
Hi thank you very much for your interest in SPACEc and this great suggestion. We constantly try to improve our pipeline and are happy about every suggestion. We might consider this idea when updating the package.
