### ISSUE TITLE
Windows installation instructions

### ISSUE THREAD

**Issue by bobbyni819** [yuqiyuqitan/SPACEc#59]
The installation instruction for Windows doesn't include libvips and openslide, which the system prompted me to install through error messages when I tried to install SPACEc.

**Comment by TKempchen** [comment]
Hi thank you for pointing this out. Installing libvips and openslide on Windows is a bit more difficult than on Unix-based systems. Therefore, we included a short helper script to set it up that should run when you first load SPACEc. This works on most systems but not on all and we are currently working on a solution. If you experience libvips errors when loading SPACEc, please try to install libvips on your system using the official instructions: https://www.libvips.org/install.html 
I hope that helps you to continue with your analysis.

**Comment by mgbckr** [comment]
Using WSL on Windows would also be an option, I think? Maybe that should be our go-to, to avoid having to support too many OSs?

**Comment by TKempchen** [comment]
WSL2 on Windows works well with SPACEc. I tested this recently.
