### ISSUE TITLE
Run container on High Performance computing cluster (HPC)

### ISSUE THREAD

**Issue by ryao-mdanderson** [yuqiyuqitan/SPACEc#60]
Dear author,

It is great that a docker container updated on github 4 months ago. May you please briefly explain -p 8888:8888 and -p 5100:5100?  Due to the security limitation, HPC does not use docker, instead of use apptainer,  I wonder if there is an instruction how to run container as apptainer / singularity on HPC cluster?  such as : 
     $ apptainer run spacec_cpu.sif  ...

Thank you very much for your reply. 
Rong Yao

**Comment by ryao-mdanderson** [comment]
Dear author @yuqiyuqitan,

If you happen to know how the container works on HPC cluster, I appreciate your suggestion.

Thanks!

**Comment by TKempchen** [comment]
Hi,

the container was designed for interactive use. The exposed ports are for a Jupyter notebook session 8888 and the TissUUmaps viewer 5100. We haven't tried to run the container as Apptainer on HPC but I think this should work as described here: https://apptainer.org/docs/user/main/docker_and_oci.html

Feel free to reopen the issue if this is not working.

**Comment by ryao-mdanderson** [comment]
Thank you @TKempchen for your reply.

Although I still do know how to run as a sif container on HPC cluster, however, I have conda environment installed. Hope this still meets our researcher's need.

Thanks!
