### ISSUE TITLE
Cell assignments in qupath

### ISSUE THREAD

**Issue by talban14** [yuqiyuqitan/SPACEc#62]
Hi i'm wondering if there's a way to push the cell assignments from SPACEc back into qupath so i can asses their accuracy and get representative images of different regions more easily?

**Comment by TKempchen** [comment]
Hi, we don't include functionality in SPACEc to export data to qupath. However, you can export the adata object or a csv file and then use these in any other program (if the program supports these file formats). If you need the segmentation masks you can get them from the pickle object that is saved during the segmentation step (notebook 1). I would suggest trying our integration with TissUUmaps, maybe this is already what you need (interactive viewer for easy visualization of the identified cells on top of the original images). I hope this helps you with your analysis!
