### ISSUE TITLE
example images for practice (S1121_Scan1_small.qptiff)

### ISSUE THREAD

**Issue by KunHHE** [yuqiyuqitan/SPACEc#64]
Hi @mgbckr, very cool tool developed. I wondered if I could get the example images for practice using the notebook?
tests/data/raw/S1121_Scan1_small.qptiff

Thanks!!!

**Comment by yuqiyuqitan** [comment]
We didnt end up sharing the qptiff file. But you can use the tif file from here to test out the rest of the computational pipeline. https://datadryad.org/stash/landing/show?id=doi%3A10.5061%2Fdryad.brv15dvj1
