### ISSUE TITLE
HELP wanted! stellar annotation method error with "cell_type"

### ISSUE THREAD

**Issue by KunHHE** [yuqiyuqitan/SPACEc#66]
Hi @yuqiyuqitan, I successfully went through notebook 0, 1, and 2, and was stopped at stellar annotation step. 
In the tutorial: 
adata = sc.read(output_dir + "adata_nn_demo_annotated.h5ad")
adata_train = adata[adata.obs['condition'] == 'tonsil']
adata_val  = adata[adata.obs['condition'] == 'tonsillitis'];

import numpy as np
np.isnan(adata_train.X).sum()

adata_train = adata_train[0:1000, :]
adata_val = adata_val[0:1000, :]

adata_new = sp.tl.adata_stellar(adata_train, 
               adata_val, 
               celltype_col = "cell_type", 
               x_col = 'x', 
               y_col = 'y', 
               sample_rate = 0.5, 
               distance_thres = 50,
               STELLAR_path = STELLAR_path)

1. My question is reference datasets are scRNA-seq or spatial transcriptomic datasets?

2. However, in the real-world data process, we will have tofind a h5ad scRNA-seq reference as input for cell type annotation, then I tried:
adata_train = sc.read(output_dir + "adata_nn_tonsil.h5ad")
adata_train

adata_val = sc.read("C:/Users/hekun/Downloads/adata_nn_demo_tonsil.h5ad")
adata_val

import numpy as np
np.isnan(adata_train.X).sum()

adata_train = adata_train[0:1000, :]
adata_val = adata_val[0:1000, :]

adata_new = sp.tl.adata_stellar(adata_train, 
               adata_val, 
               celltype_col = "cell_type", 
               x_col = 'x', 
               y_col = 'y', 
               sample_rate = 0.5, 
               distance_thres = 50,
               STELLAR_path = STELLAR_path); 
Here I met an error: The adata_train is the data need to be annotated based on adata_val as reference, which contain "cell_type" index. The adata_train doesn't include any "cell_type" index. But I don't know why this error jumped out. Any comments? 

KeyError                                  Traceback (most recent call last)
Cell In[75], line 1
----> 1 adata_new = sp.tl.adata_stellar(adata_train, 
      2                adata_val, 
      3                celltype_col = "cell_type", 
      4                x_col = 'x', 
      5                y_col = 'y', 
      6                sample_rate = 0.5, 
      7                distance_thres = 50,
      8                STELLAR_path = STELLAR_path)

File ~\miniconda3\envs\spacec\lib\site-packages\spacec\tools\_general.py:2804, in adata_stellar(adata_train, adata_unannotated, celltype_col, x_col, y_col, sample_rate, distance_thres, epochs, key_added, STELLAR_path)
   2801 train_df = adata_train.to_df()
   2803 # add to train_df
-> 2804 positions_celltype = adata_train.obs[[x_col, y_col, celltype_col]]
   2806 train_df = pd.concat([train_df, positions_celltype], axis=1)
   2808 train_df = train_df.sample(n=round(sample_rate * len(train_df)), random_state=1)

File ~\miniconda3\envs\spacec\lib\site-packages\pandas\core\frame.py:4108, in DataFrame.__getitem__(self, key)
   4106     if is_iterator(key):
   4107         key = list(key)
-> 4108     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   4110 # take() does not accept boolean indexers
   4111 if getattr(indexer, "dtype", None) == bool:

File ~\miniconda3\envs\spacec\lib\site-packages\pandas\core\indexes\base.py:6200, in Index._get_indexer_strict(self, key, axis_name)
   6197 else:
   6198     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6200 self._raise_if_missing(keyarr, indexer, axis_name)
   6202 keyarr = self.take(indexer)
   6203 if isinstance(key, Index):
   6204     # GH 42790 - Preserve name from an Index

File ~\miniconda3\envs\spacec\lib\site-packages\pandas\core\indexes\base.py:6252, in Index._raise_if_missing(self, key, indexer, axis_name)
   6249     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6251 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6252 raise KeyError(f"{not_found} not in index")

KeyError: "['cell_type'] not in index"

**Comment by TKempchen** [comment]
Hi, thank you for using SPACEc! 

1) STELLAR is used to transfer labels based on shared features. It learns from marker expression and positioning of cells in the reference and transfers the labels + predict potential new labels in the validation dataset. As input, you should use a dataset that is similar and contains spatial (xy) data. Here is the original paper for reference and further information: https://www.nature.com/articles/s41592-022-01651-8

2) It looks like the dataset used for training simply does not contain the cell_type column (you might inputted the not annotated one). This column should refer to your labels. The function defaults to 'cell_type'; However, you can change the used label column's name based on how you called it with the celltype_col parameter. 

I hope that helps you to continue with your analyses.
